<h1>Chapter 8 - Semantic Search and Retrieval-Augmented Generation</h1>
<i>Exploring a vital part of LLMs, search.</i>

<a href="https://www.amazon.com/Hands-Large-Language-Models-Understanding/dp/1098150961"><img src="https://img.shields.io/badge/Buy%20the%20Book!-grey?logo=amazon"></a>
<a href="https://www.oreilly.com/library/view/hands-on-large-language/9781098150952/"><img src="https://img.shields.io/badge/O'Reilly-white.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB3aWR0aD0iMzQiIGhlaWdodD0iMjciIHZpZXdCb3g9IjAgMCAzNCAyNyIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTMiIGN5PSIxNCIgcj0iMTEiIHN0cm9rZT0iI0Q0MDEwMSIgc3Ryb2tlLXdpZHRoPSI0Ii8+CjxjaXJjbGUgY3g9IjMwLjUiIGN5PSIzLjUiIHI9IjMuNSIgZmlsbD0iI0Q0MDEwMSIvPgo8L3N2Zz4K"></a>
<a href="https://github.com/HandsOnLLM/Hands-On-Large-Language-Models"><img src="https://img.shields.io/badge/GitHub%20Repository-black?logo=github"></a>
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/HandsOnLLM/Hands-On-Large-Language-Models/blob/main/chapter08/Chapter%208%20-%20Semantic%20Search.ipynb)

---

This notebook is for Chapter 8 of the [Hands-On Large Language Models](https://www.amazon.com/Hands-Large-Language-Models-Understanding/dp/1098150961) book by [Jay Alammar](https://www.linkedin.com/in/jalammar) and [Maarten Grootendorst](https://www.linkedin.com/in/mgrootendorst/).

---

<a href="https://www.amazon.com/Hands-Large-Language-Models-Understanding/dp/1098150961">
<img src="https://raw.githubusercontent.com/HandsOnLLM/Hands-On-Large-Language-Models/main/images/book_cover.png" width="350"/></a>

### [OPTIONAL] - Installing Packages on <img src="https://colab.google/static/images/icons/colab.png" width=100>

If you are viewing this notebook on Google Colab (or any other cloud vendor), you need to **uncomment and run** the following codeblock to install the dependencies for this chapter:

---

💡 **NOTE**: We will want to use a GPU to run the examples in this notebook. In Google Colab, go to
**Runtime > Change runtime type > Hardware accelerator > GPU > GPU type > T4**.

---

In [1]:
# %%capture
# !pip install langchain==0.2.5 faiss-cpu==1.8.0 cohere==5.5.8 langchain-community==0.2.5 rank_bm25==0.2.2 sentence-transformers==3.0.1
# !pip install llama-cpp-python==0.2.78  --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124

# Dense Retrieval Example

## 1. Getting the text archive and chunking it

In [6]:
import cohere

# Paste your API key here. Remember to not share publicly
api_key = ''

# Create and retrieve a Cohere API key from os.cohere.ai
co = cohere.Client(api_key)

In [7]:
text = """
Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan.
It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine.
Set in a dystopian future where humanity is struggling to survive, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for mankind.

Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007.
Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar.
Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm.
Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles.
Interstellar uses extensive practical and miniature effects and the company Double Negative created additional digital effects.

Interstellar premiered on October 26, 2014, in Los Angeles.
In the United States, it was first released on film stock, expanding to venues using digital projectors.
The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014.
It received acclaim for its performances, direction, screenplay, musical score, visual effects, ambition, themes, and emotional weight.
It has also received praise from many astronomers for its scientific accuracy and portrayal of theoretical astrophysics. Since its premiere, Interstellar gained a cult following,[5] and now is regarded by many sci-fi experts as one of the best science-fiction films of all time.
Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades"""

# Split into a list of sentences
texts = text.split('.') # 根据句号（.）作为分隔符，将 text 字符串分割成多个子字符串，并将这些子字符串存储在一个列表中。

# Clean up to remove empty spaces and new lines
texts = [t.strip(' \n') for t in texts] # 去除字符串 t 前后的空格（）和换行符（\n）。

## 2. Embedding the Text Chunks

In [10]:
import numpy as np

# Get the embeddings
response = co.embed( # Cohere 提供的用于获取文本嵌入向量的方法。
  texts=texts,
  input_type="search_document", # 指定输入的类型为搜索文档，Cohere 模型会根据这个类型对输入文本进行相应的处理，以生成适合搜索场景的嵌入向量。
).embeddings # 从 co.embed() 方法的返回结果中提取嵌入向量，存储在 response 变量中。response 是一个列表，列表中的每个元素是一个表示对应文本的嵌入向量。

embeds = np.array(response)
print(embeds.shape)

(15, 4096)

## 3. Building The Search Index

In [13]:
import faiss # 一个用于高效相似性搜索和密集向量聚类的库

dim = embeds.shape[1] # embeds.shape[1] 表示数组第二维的大小，即每个嵌入向量的维度。
index = faiss.IndexFlatL2(dim) # Faiss 中用于创建基于欧几里得距离（L2 距离）的扁平索引的类。
index.add(np.float32(embeds)) # embeds 中的所有嵌入向量都会被添加到 Faiss 索引中，后续可以使用该索引进行快速的相似度搜索。

## 4. Search the index

In [14]:
import pandas as pd

def search(query, number_of_results=3):

  # 1. Get the query's embedding 获取查询文本的嵌入向量
  query_embed = co.embed(texts=[query],
                input_type="search_query",).embeddings[0]

  # 2. Retrieve the nearest neighbors
  distances , similar_item_ids = index.search(np.float32([query_embed]), number_of_results)
  # distances：存储查询向量与找到的最近邻向量之间的欧几里得距离。
  # similar_item_ids：存储最近邻向量在索引中的索引。

  # 3. Format the results
  texts_np = np.array(texts) # Convert texts list to numpy for easier indexing
  results = pd.DataFrame(data={'texts': texts_np[similar_item_ids[0]],
                              'distance': distances[0]})

  # 4. Print and return the results
  print(f"Query:'{query}'\nNearest neighbors:")
  return results

In [15]:
query = "how precise was the science"
results = search(query)
results

Query:'how precise was the science'
Nearest neighbors:

                                               texts      distance
0  It has also received praise from many astronom...  10757.371094
1  Caltech theoretical physicist and 2017 Nobel l...  11566.136719
2  Interstellar uses extensive practical and mini...  11922.841797

In [17]:
from rank_bm25 import BM25Okapi
from sklearn.feature_extraction import _stop_words # 停用词是指在文本中频繁出现但对文本的语义和主题表达没有太大贡献的词汇，如 “the”、“and”、“is” 等
import string

def bm25_tokenizer(text):
    tokenized_doc = []
    for token in text.lower().split(): # 将输入的文本转换为小写，并按空格分割成多个词元。
        token = token.strip(string.punctuation) # 去除词元前后的标点符号。

        if len(token) > 0 and token not in _stop_words.ENGLISH_STOP_WORDS: # 检查词元的长度是否大于 0，避免将空字符串添加到结果列表中。是否不在英文停用词列表中
            tokenized_doc.append(token)
    return tokenized_doc

In [18]:
from tqdm import tqdm

tokenized_corpus = []
for passage in tqdm(texts):
    tokenized_corpus.append(bm25_tokenizer(passage))

bm25 = BM25Okapi(tokenized_corpus) # 该模型会根据分词后的文本集合计算每个词元的统计信息，如词频、文档频率等

100%|██████████| 15/15 [00:00<00:00, 72398.80it/s]

In [21]:
def keyword_search(query, top_k=3, num_candidates=15):
    print("Input question:", query)

    ##### BM25 search (lexical search) #####
    bm25_scores = bm25.get_scores(bm25_tokenizer(query))
    top_n = np.argpartition(bm25_scores, -num_candidates)[-num_candidates:] # numpy 库中的函数，用于对数组进行分区操作。[-num_candidates:] 表示取分区后数组的最后 num_candidates 个元素。
    bm25_hits = [{'corpus_id': idx, 'score': bm25_scores[idx]} for idx in top_n]
    bm25_hits = sorted(bm25_hits, key=lambda x: x['score'], reverse=True)

    print(f"Top-3 lexical search (BM25) hits")
    for hit in bm25_hits[0:top_k]:
        print("\t{:.3f}\t{}".format(hit['score'], texts[hit['corpus_id']].replace("\n", " ")))

In [20]:
keyword_search(query = "how precise was the science")

Input question: how precise was the science
Top-3 lexical search (BM25) hits
	1.789	Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan
	1.373	Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar
	0.000	It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine

## Caveats of Dense Retrieval 密集检索的注意事项

In [22]:
query = "What is the mass of the moon?"
results = search(query)
results

Query:'What is the mass of the moon?'
Nearest neighbors:

                                               texts      distance
0  Cinematographer Hoyte van Hoytema shot it on 3...  12854.445312
1  The film had a worldwide gross over $677 milli...  13301.009766
2  It has also received praise from many astronom...  13332.000000

# Reranking Example

In [24]:
query = "how precise was the science"
results = co.rerank(query=query, documents=texts, top_n=3, return_documents=True)
results.results

[RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='It has also received praise from many astronomers for its scientific accuracy and portrayal of theoretical astrophysics'), index=12, relevance_score=0.16981852),
 RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014'), index=10, relevance_score=0.07004896),
 RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar'), index=4, relevance_score=0.0043994132)]

In [25]:
for idx, result in enumerate(results.results):
    print(idx, result.relevance_score , result.document.text)

0 0.16981852 It has also received praise from many astronomers for its scientific accuracy and portrayal of theoretical astrophysics
1 0.07004896 The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014
2 0.0043994132 Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar

In [27]:
def keyword_and_reranking_search(query, top_k=3, num_candidates=10):
    print("Input question:", query)

    ##### BM25 search (lexical search) #####
    bm25_scores = bm25.get_scores(bm25_tokenizer(query))
    top_n = np.argpartition(bm25_scores, -num_candidates)[-num_candidates:]
    bm25_hits = [{'corpus_id': idx, 'score': bm25_scores[idx]} for idx in top_n] # 创建一个包含候选文档信息的列表 bm25_hits，每个元素是一个字典，包含文档索引 corpus_id 和 BM25 得分 score。
    bm25_hits = sorted(bm25_hits, key=lambda x: x['score'], reverse=True)

    print(f"Top-3 lexical search (BM25) hits")
    for hit in bm25_hits[0:top_k]:
        print("\t{:.3f}\t{}".format(hit['score'], texts[hit['corpus_id']].replace("\n", " ")))

    #Add re-ranking
    docs = [texts[hit['corpus_id']] for hit in bm25_hits] # 从 bm25_hits 中提取候选文档的内容，存储在 docs 列表中

    print(f"\nTop-3 hits by rank-API ({len(bm25_hits)} BM25 hits re-ranked)")
    results = co.rerank(query=query, documents=docs, top_n=top_k, return_documents=True)
    for hit in results.results:
        print("\t{:.3f}\t{}".format(hit.relevance_score, hit.document.text.replace("\n", " ")))

In [30]:
keyword_and_reranking_search(query = "how precise was the science")

Input question: how precise was the science
Top-3 lexical search (BM25) hits
	1.789	Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan
	1.373	Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar
	0.000	Interstellar uses extensive practical and miniature effects and the company Double Negative created additional digital effects

Top-3 hits by rank-API (10 BM25 hits re-ranked)
	0.004	Caltech theoretical physicist and 2017 Nobel laureate in Physics[4] Kip Thorne was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar
	0.004	Set in a dystopian future where humanity is struggling to survive, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for mankind
	0.003	Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007

# Retrieval-Augmented Generation

## Example: Grounded Generation with an LLM API

In [32]:
query = "income generated"

# 1- Retrieval
# We'll use embedding search. But ideally we'd do hybrid
results = search(query)

# 2- Grounded Generation
docs_dict = [{'text': text} for text in results['texts']] # 字典的键为 'text'，值为文档文本，存储在 docs_dict 列表中。这样做是为了符合 Cohere 聊天 API 对文档输入的格式要求。
response = co.chat( # 是 Cohere 提供的聊天 API 方法，用于进行基于上下文的文本生成。
    message = query,
    documents=docs_dict
)

print(response.text)

Query:'income generated'
Nearest neighbors:
The film Interstellar grossed over $677 million worldwide, and $773 million with subsequent re-releases.

In [33]:
response

NonStreamedChatResponse(text='The film Interstellar grossed over $677 million worldwide, and $773 million with subsequent re-releases.', generation_id='d9fbeb9e-50c7-48c4-a6ff-4042b3b45659', citations=[ChatCitation(start=30, end=104, text='over $677 million worldwide, and $773 million with subsequent re-releases.', document_ids=['doc_0'], type='TEXT_CONTENT')], documents=[{'id': 'doc_0', 'text': 'The film had a worldwide gross over $677 million (and $773 million with subsequent re-releases), making it the tenth-highest grossing film of 2014'}], is_search_required=None, search_queries=None, search_results=None, finish_reason='COMPLETE', tool_calls=None, chat_history=[Message_User(message='income generated', tool_calls=None, role='USER'), Message_Chatbot(message='The film Interstellar grossed over $677 million worldwide, and $773 million with subsequent re-releases.', tool_calls=None, role='CHATBOT')], prompt=None, meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(input_tokens=106, output_tokens=25, search_units=None, classifications=None), tokens=ApiMetaTokens(input_tokens=800, output_tokens=68), warnings=None), response_id='dcca1825-26ce-4ddb-ac31-c5fe827f3664')

In [34]:
response.citations

[ChatCitation(start=30, end=104, text='over $677 million worldwide, and $773 million with subsequent re-releases.', document_ids=['doc_0'], type='TEXT_CONTENT')]

## Example: RAG with Local Models

### Loading the Generation Model

In [35]:
!wget https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf

--2025-03-12 07:44:46--  https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf
Resolving huggingface.co (huggingface.co)... 54.230.71.103, 54.230.71.28, 54.230.71.56, ...
Connecting to huggingface.co (huggingface.co)|54.230.71.103|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs-us-1.hf.co/repos/41/c8/41c860f65b01de5dc4c68b00d84cead799d3e7c48e38ee749f4c6057776e2e9e/8a83c7fb9049a9b2e92266fa7ad04933bb53aa1e85136b7b30f1b8000ff2edef?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Phi-3-mini-4k-instruct-q4.gguf%3B+filename%3D%22Phi-3-mini-4k-instruct-q4.gguf%22%3B&Expires=1741769086&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc0MTc2OTA4Nn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzQxL2M4LzQxYzg2MGY2NWIwMWRlNWRjNGM2OGIwMGQ4NGNlYWQ3OTlkM2U3YzQ4ZTM4ZWU3NDlmNGM2MDU3Nzc2ZTJlOWUvOGE4M2M3ZmI5MDQ5YTliMmU5MjI2NmZhN2FkMDQ5MzNiYjUzYWExZTg1MTM2YjdiMzBmMWI4MDAwZmYyZWRlZj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=A1OC1929edku5c%7E7nrceynHccDxnkaI2wZf1tqyTJdYcvrbkz6JJKWDcZ5KlimsGd%7EiGTkfZHfsSFLODEJtzUOen9JM1-5jLLZ1H%7Ec-cLM6Yu69dxh4V2D%7EjKlVX8sbvz0XcPs-RVV9KyvoHD6uww7l4y0KWQMCLw36lyaA9pIO6VTP9hyUVlcDHnpexlN31znPwCwX6bgYcq1FgjXcAHffQAwa2rcZKqp4bBXslruidU9Q8QD3pqTScwlwgJc340X3wG4ozXfKeZ0-6Fs2xenWDs8UczLkT5zSuGFpTYL1%7EnGTpvnxtmnhKkWD1YWjjxIwQy6kYCe%7ECq29sU7o21Q__&Key-Pair-Id=K24J24Z295AEI9 [following]
--2025-03-12 07:44:46--  https://cdn-lfs-us-1.hf.co/repos/41/c8/41c860f65b01de5dc4c68b00d84cead799d3e7c48e38ee749f4c6057776e2e9e/8a83c7fb9049a9b2e92266fa7ad04933bb53aa1e85136b7b30f1b8000ff2edef?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Phi-3-mini-4k-instruct-q4.gguf%3B+filename%3D%22Phi-3-mini-4k-instruct-q4.gguf%22%3B&Expires=1741769086&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc0MTc2OTA4Nn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzQxL2M4LzQxYzg2MGY2NWIwMWRlNWRjNGM2OGIwMGQ4NGNlYWQ3OTlkM2U3YzQ4ZTM4ZWU3NDlmNGM2MDU3Nzc2ZTJlOWUvOGE4M2M3ZmI5MDQ5YTliMmU5MjI2NmZhN2FkMDQ5MzNiYjUzYWExZTg1MTM2YjdiMzBmMWI4MDAwZmYyZWRlZj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=A1OC1929edku5c%7E7nrceynHccDxnkaI2wZf1tqyTJdYcvrbkz6JJKWDcZ5KlimsGd%7EiGTkfZHfsSFLODEJtzUOen9JM1-5jLLZ1H%7Ec-cLM6Yu69dxh4V2D%7EjKlVX8sbvz0XcPs-RVV9KyvoHD6uww7l4y0KWQMCLw36lyaA9pIO6VTP9hyUVlcDHnpexlN31znPwCwX6bgYcq1FgjXcAHffQAwa2rcZKqp4bBXslruidU9Q8QD3pqTScwlwgJc340X3wG4ozXfKeZ0-6Fs2xenWDs8UczLkT5zSuGFpTYL1%7EnGTpvnxtmnhKkWD1YWjjxIwQy6kYCe%7ECq29sU7o21Q__&Key-Pair-Id=K24J24Z295AEI9
Resolving cdn-lfs-us-1.hf.co (cdn-lfs-us-1.hf.co)... 13.35.186.54, 13.35.186.39, 13.35.186.84, ...
Connecting to cdn-lfs-us-1.hf.co (cdn-lfs-us-1.hf.co)|13.35.186.54|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2393231072 (2.2G) [binary/octet-stream]
Saving to: ‘Phi-3-mini-4k-instruct-q4.gguf’

Phi-3-mini-4k-instr 100%[===================>]   2.23G   121MB/s    in 25s

2025-03-12 07:45:11 (92.4 MB/s) - ‘Phi-3-mini-4k-instruct-q4.gguf’ saved [2393231072/2393231072]

In [36]:
from langchain import LlamaCpp

# Make sure the model path is correct for your system!
llm = LlamaCpp(
    model_path="Phi-3-mini-4k-instruct-q4.gguf",
    n_gpu_layers=-1,
    max_tokens=500,
    n_ctx=2048,
    seed=42,
    verbose=False
)

### Loading the Embedding Model

In [37]:
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

# Embedding Model for converting text to numerical representations
embedding_model = HuggingFaceEmbeddings(
    model_name='BAAI/bge-small-en-v1.5'
)

<ipython-input-37-ee18e4d56182>:4: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  embedding_model = HuggingFaceEmbeddings(
/usr/local/lib/python3.11/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

### Preparing the Vector Database

In [38]:
from langchain.vectorstores import FAISS

# Create a local vector database
db = FAISS.from_texts(texts, embedding_model) # 这是 FAISS 类提供的一个类方法，用于从文本列表创建向量数据库。
# embedding_model：这是一个嵌入模型对象，用于将文本转换为向量表示。

### The RAG Prompt

In [39]:
from langchain import PromptTemplate
from langchain.chains import RetrievalQA


# Create a prompt template
template = """<|user|>
Relevant information:
{context}

Provide a concise answer the following question using the relevant information provided above:
{question}<|end|>
<|assistant|>"""
prompt = PromptTemplate(
    template=template,
    input_variables=["context", "question"]
)

# RAG Pipeline
rag = RetrievalQA.from_chain_type( # 用于根据指定的链类型创建一个 RAG 问答链。
    llm=llm,
    chain_type='stuff', # 指定检索和生成的组合方式。'stuff' 是一种常见的链类型，它会将检索到的所有相关文档一次性 “塞进” 提示（prompt）中，然后将提示和问题一起输入给大语言模型进行回答。
    retriever=db.as_retriever(), # 指定用于检索相关文档的检索器。
    chain_type_kwargs={
        "prompt": prompt
    },
    verbose=True
)

In [40]:
rag.invoke('Income generated')

> Entering new RetrievalQA chain...

> Finished chain.

{'query': 'Income generated',
 'result': ' The provided information does not directly relate to income generation. However, considering the success of "Interstellar" as mentioned (the involvement of Kip Thorne and its release methods), it can be inferred that "Interstellar" was a commercially successful film which likely contributed positively to income generated through box office sales and ancillary revenue streams such as home media, streaming rights, and the tie-in book. But specific financial figures are not given in the information provided.'}